### PR TITLE
Fix URL to setting up dev env

### PR DESCRIPTION
**Pull request by whatasunnyday**
If you go to http://ryanbigg.com/ and click 

Once you've got Ubuntu setup, you can follow my Ubuntu, Ruby, ruby-install, chruby, Rails and You blog post which will setup a proper development environment for you on Ubuntu.

it will 404.

### CODE REVIEW

**Comment by radar** [comment]
Thank you!

**Comment by radar** [comment]
Actually, for this you'll need to edit the blog post itself. Can you please submit a new PR that edits the blog post in `_posts` and then run `jekyll build` on that to update the content? That would great!

**Comment by whatasunnyday** [comment]
@radar Would you like me to rebase the previous commit merged into master? Or just add an additional commit?

**Comment by radar** [comment]
Please create a new PR for this

**Pull request merged**
